/**
 * Reports what is in the database and which of it looks like development data.
 *
 *   npm run db:audit            — report only, changes nothing
 *   npm run db:audit -- --purge — delete ONLY what it classified as generated
 *
 * This exists because "the app used to run in demo mode" is not a reason to
 * drop a table. A workspace can hold a mixture: orders generated by the old
 * seed sit in the same table as orders retrieved from eBay, and only one of
 * those is safe to remove.
 *
 * Classification is conservative and evidence-based. A record is called
 * GENERATED only when something about it could not have come from the live
 * API. Anything else is reported as REVIEW and never deleted, even with
 * --purge — if this script cannot prove a record is synthetic, a human
 * decides.
 */

import path from "node:path";

import { loadEnvConfig } from "@next/env";

loadEnvConfig(path.resolve(import.meta.dirname, ".."), true, {
  info: () => {},
  error: console.error,
});

import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

/** Spreadsheet ids shipped by the old demo fixtures. */
const RETIRED_FIXTURE_SPREADSHEET_IDS = [
  "1aBcD_demo_order_tracker_0001",
  "1aBcD_demo_warehouse_0002",
  "1aBcD_demo_accounting_0003",
];

/** Account identifiers the old "use demo connection" action wrote. */
const RETIRED_DEMO_ACCOUNTS = ["demo_seller_acct", "demo-ebay-user-0001"];

interface Finding {
  table: string;
  verdict: "GENERATED" | "REVIEW";
  count: number;
  why: string;
  ids: string[];
}

function line(label: string, value: string | number) {
  console.log(`    ${label.padEnd(32)} ${value}`);
}

async function main() {
  const purge = process.argv.includes("--purge");
  const findings: Finding[] = [];

  console.log("\n  Database audit\n");
  console.log(`    mode                             ${purge ? "PURGE" : "report only"}`);

  /* --- Inventory --------------------------------------------------------- */
  const [users, ebayConns, googleConns, sheets, orders, lineItems, jobs, logs, results] =
    await Promise.all([
      prisma.user.count(),
      prisma.ebayConnection.count(),
      prisma.googleConnection.count(),
      prisma.googleSheetConfig.count(),
      prisma.importedOrder.count(),
      prisma.orderLineItem.count(),
      prisma.syncJob.count(),
      prisma.syncLog.count(),
      prisma.syncOrderResult.count(),
    ]);

  console.log("\n  Inventory\n");
  line("users", users);
  line("eBay connections", ebayConns);
  line("Google connections", googleConns);
  line("sheet configurations", sheets);
  line("imported orders", orders);
  line("order line items", lineItems);
  line("sync jobs", jobs);
  line("sync logs", logs);
  line("per-order sync results", results);

  /* --- Generated: fixture spreadsheets ------------------------------------ */
  const fixtureConfigs = await prisma.googleSheetConfig.findMany({
    where: { spreadsheetId: { in: RETIRED_FIXTURE_SPREADSHEET_IDS } },
    select: { id: true, spreadsheetId: true, spreadsheetName: true },
  });
  if (fixtureConfigs.length > 0) {
    findings.push({
      table: "GoogleSheetConfig",
      verdict: "GENERATED",
      count: fixtureConfigs.length,
      why: "Points at a spreadsheet id that only ever existed in the removed demo fixtures — no such file exists in any Google account.",
      ids: fixtureConfigs.map((c) => `${c.id} (${c.spreadsheetId})`),
    });
  }

  /* --- Generated: placeholder connections --------------------------------- */
  const demoEbay = await prisma.ebayConnection.findMany({
    where: {
      OR: [
        { ebayUsername: { in: RETIRED_DEMO_ACCOUNTS } },
        { ebayUserId: { in: RETIRED_DEMO_ACCOUNTS } },
      ],
    },
    select: { id: true, ebayUsername: true },
  });
  if (demoEbay.length > 0) {
    findings.push({
      table: "EbayConnection",
      verdict: "GENERATED",
      count: demoEbay.length,
      why: "Carries the placeholder account identifier written by the removed 'use demo connection' action. It holds no tokens and cannot call eBay.",
      ids: demoEbay.map((c) => `${c.id} (${c.ebayUsername})`),
    });
  }

  /* --- The decisive question: has eBay ever answered this deployment? ----- */
  //
  // Every outbound eBay request is recorded in EbayApiCall, including the ones
  // that failed. If not one has ever succeeded, then no order in this database
  // can have come from eBay — whatever it is, something else put it there.
  //
  // This is the strongest evidence available and it cannot misfire on a real
  // deployment: a workspace that has genuinely imported an order necessarily
  // has a successful call on record.
  const successfulEbayCalls = await prisma.ebayApiCall.count({ where: { ok: true } });
  const everConnected = await prisma.ebayConnection.count({
    where: { OR: [{ accessToken: { not: null } }, { lastApiSuccessAt: { not: null } }] },
  });
  const ebayNeverWorked = successfulEbayCalls === 0 && everConnected === 0;

  console.log("\n  Evidence\n");
  line("successful eBay API calls ever", successfulEbayCalls);
  line("connections that held a token", everConnected);
  if (ebayNeverWorked) {
    console.log(
      "\n    eBay has never successfully answered this deployment, so no stored\n" +
        "    order or sync run can have originated from it.",
    );
  }

  if (ebayNeverWorked) {
    const allOrders = await prisma.importedOrder.findMany({
      select: { id: true, ebayOrderId: true },
    });
    if (allOrders.length > 0) {
      findings.push({
        table: "ImportedOrder",
        verdict: "GENERATED",
        count: allOrders.length,
        why: "eBay has never returned a successful response to this deployment, so no order here came from the eBay API.",
        ids: allOrders.slice(0, 20).map((o) => o.ebayOrderId),
      });
    }

    const allJobs = await prisma.syncJob.count();
    if (allJobs > 0) {
      findings.push({
        table: "SyncJob",
        verdict: "GENERATED",
        count: allJobs,
        why: "Sync history for runs that could not have happened: no eBay call has ever succeeded. Logs and per-order results are removed with them.",
        ids: [],
      });
    }
  } else {
    // eBay has worked at some point, so orders must be judged individually.
    const orphanOrders = await prisma.importedOrder.findMany({
      where: { ebayConnectionId: null, rawPayloadJson: null },
      select: { id: true, ebayOrderId: true },
    });
    if (orphanOrders.length > 0) {
      findings.push({
        table: "ImportedOrder",
        verdict: "GENERATED",
        count: orphanOrders.length,
        why: "No originating eBay connection and no stored payload. A live import records both.",
        ids: orphanOrders.slice(0, 20).map((o) => o.ebayOrderId),
      });
    }

    const demoConnectionIds = demoEbay.map((c) => c.id);
    if (demoConnectionIds.length > 0) {
      const viaDemo = await prisma.importedOrder.count({
        where: { ebayConnectionId: { in: demoConnectionIds } },
      });
      if (viaDemo > 0) {
        findings.push({
          table: "ImportedOrder",
          verdict: "REVIEW",
          count: viaDemo,
          why: "Attributed to a placeholder connection, but this deployment has also made real eBay calls — confirm before removing.",
          ids: [],
        });
      }
    }
  }

  /* --- Report ------------------------------------------------------------ */
  console.log("\n  Findings\n");
  if (findings.length === 0) {
    console.log("    Nothing identifiable as development data.\n");
  } else {
    for (const finding of findings) {
      console.log(`    [${finding.verdict}] ${finding.table} × ${finding.count}`);
      console.log(`        ${finding.why}`);
      if (finding.ids.length > 0) {
        console.log(`        e.g. ${finding.ids.slice(0, 5).join(", ")}`);
      }
      console.log("");
    }
  }

  const generated = findings.filter((f) => f.verdict === "GENERATED");
  const review = findings.filter((f) => f.verdict === "REVIEW");

  if (!purge) {
    if (generated.length > 0) {
      console.log(
        `    ${generated.reduce((n, f) => n + f.count, 0)} record(s) can be removed with:  npm run db:audit -- --purge\n`,
      );
    }
    if (review.length > 0) {
      console.log(
        `    ${review.reduce((n, f) => n + f.count, 0)} record(s) need a human decision and are never purged automatically.\n`,
      );
    }
    return;
  }

  /* --- Purge (GENERATED only) -------------------------------------------- */
  console.log("  Purging records classified GENERATED…\n");

  for (const finding of generated) {
    if (finding.table === "ImportedOrder") {
      // Line items, fulfillments and per-order sync results cascade.
      const { count } = ebayNeverWorked
        ? await prisma.importedOrder.deleteMany({})
        : await prisma.importedOrder.deleteMany({
            where: { ebayConnectionId: null, rawPayloadJson: null },
          });
      line("imported orders deleted", count);
    }
    if (finding.table === "SyncJob") {
      // Logs and per-order results cascade from the job.
      const { count } = await prisma.syncJob.deleteMany({});
      line("sync jobs deleted", count);
      // Row links point at sheet rows that were never really written.
      const links = await prisma.sheetRowLink.deleteMany({});
      line("sheet row links deleted", links.count);
    }
  }
  if (fixtureConfigs.length > 0) {
    const { count } = await prisma.googleSheetConfig.deleteMany({
      where: { id: { in: fixtureConfigs.map((c) => c.id) } },
    });
    line("sheet configurations deleted", count);
  }
  if (demoEbay.length > 0) {
    const { count } = await prisma.ebayConnection.deleteMany({
      where: { id: { in: demoEbay.map((c) => c.id) } },
    });
    line("eBay connections deleted", count);
  }

  console.log(
    "\n    Records marked REVIEW were left alone. Inspect them and delete by id if you are sure.\n",
  );
}

main()
  .catch((error) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(() => prisma.$disconnect());
